Reviewed: eclipse-platform-sources

diff --git a/bin/apply-patches b/bin/apply-patches
--- a/bin/apply-patches
+++ b/bin/apply-patches
@@ -30,6 +30,11 @@ fi
 for D in ${PATCHED_DIRS}
 do
 	P="${PATCH_DIR}/patch-${D}"
+	if [ ! -r ${P} ]
+	then
+		echo "ERROR: No patch file ${P}"
+		exit 1
+	fi
 	patch --directory ${AGGR_MODULE} --fuzz 0 -V none --quiet < ${P}
 	if [ $? -ne 0 ]
 	then
