completed: eclipse-platform-parent

diff --git a/bin/generate-patches b/bin/generate-patches
--- a/bin/generate-patches
+++ b/bin/generate-patches
@@ -27,6 +27,11 @@ then
 	echo "ERROR: Run this from top level"
 	exit 1
 fi
+if [ $# -gt 0 ]
+then
+	INSPECT="$*"
+fi
+
 . ./config.sh
 
 AGGR_MODULE=$(basename $ECLIPSE_TOP)
@@ -49,6 +54,11 @@ s/^(\+{3} .*	)[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{9} .[0
 
 for DIR in ${INSPECT}
 do
+	if [ ! -d ${AGGR_MODULE}/${DIR} ]
+	then
+		echo "ERROR: ${AGGR_MODULE}/${DIR} not found"
+		exit 1
+	fi
 	echo "INFO: Inspecting ${DIR}"
 	(
 		cd ${AGGR_MODULE}
